const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const epley=(kg,reps)=>Math.round((kg*(1+reps/30))*2)/2;
const seed={
  gregorio:{name:'Gregorio',initials:'GM',age:37,height:1.86,sex:'Homme',weight:85,vo2:null,
    muscles:[['Quadriceps','Élevé','high'],['Épaules','Élevé','high'],['Dos','Moyen','mid'],['Fessiers','Moyen','mid'],['Pectoraux','Faible','low']],
    profileAxes:[['Force',72],['Endurance',66],['Puissance',61],['Gymnastique',34],['Endurance musculaire',68]],
    sessions:[
      {dateISO:'2026-08-13',date:'13 août 2026',type:'Cross Training duo',family:'wod',duration:'57 min',rpe:'8.5',result:'57:00',focus:'Mixte',items:['1 km Run','Tire Push 100 m','Farmer Carry 2×18 kg','Wall Balls 6 kg','TRX','Sandbag 20 kg','Burpees','1 km Run'],real:true},
      {dateISO:'2026-08-11',date:'11 août 2026',type:'Strength',family:'strength',duration:'52 min',rpe:'8',result:'—',focus:'Force',items:['Bench Press · 75 kg × 5','Barbell Row · 70 kg × 8','DB Push Press · 20 kg × 6'],sample:true},
      {dateISO:'2026-08-08',date:'8 août 2026',type:'Running',family:'run',duration:'38 min',rpe:'6.5',result:'—',focus:'Engine',items:['Run · endurance fondamentale'],sample:true}
    ],
    refs:[
      {id:'bench',name:'Bench Press',cat:'force',primary:{label:'e1RM',value:`${epley(75,5)} kg`,kind:'estimated'},rms:{'1RM':null,'e1RM':`${epley(75,5)} kg`,'3RM':null,'5RM':'75 kg','8RM':null,'10RM':null},source:'75 kg × 5',history:[['Référence connue','75 kg × 5']],filled:true},
      {id:'row',name:'Barbell Row',cat:'force',primary:{label:'e1RM',value:`${epley(70,8)} kg`,kind:'estimated'},rms:{'1RM':null,'e1RM':`${epley(70,8)} kg`,'3RM':null,'5RM':null,'8RM':'70 kg','10RM':null},source:'70 kg × 8',history:[['Référence connue','70 kg × 8']],filled:true},
      {id:'back-squat',name:'Back Squat',cat:'force',primary:{label:'1RM',value:'À renseigner',kind:'missing'},rms:{'1RM':null,'e1RM':null,'3RM':null,'5RM':null,'8RM':null,'10RM':null},history:[],filled:false},
      {id:'front-squat',name:'Front Squat',cat:'force',primary:{label:'1RM',value:'À renseigner',kind:'missing'},rms:{'1RM':null,'e1RM':null,'3RM':null,'5RM':null},history:[],filled:false},
      {id:'deadlift',name:'Deadlift',cat:'force',primary:{label:'1RM',value:'À renseigner',kind:'missing'},rms:{'1RM':null,'e1RM':null,'3RM':null,'5RM':null,'8RM':null},history:[],filled:false},
      {id:'push-press',name:'DB Push Press',cat:'haltero',primary:{label:'e1RM',value:`${epley(20,6)} kg / halt.`,kind:'estimated'},rms:{'1RM':null,'e1RM':`${epley(20,6)} kg / halt.`,'3RM':null,'5RM':null,'6RM':'20 kg / halt.'},source:'20 kg × 6 / haltère',history:[['Référence connue','20 kg × 6']],filled:true},
      {id:'snatch',name:'Snatch',cat:'haltero',primary:{label:'1RM',value:'À renseigner',kind:'missing'},rms:{'1RM':null,'e1RM':null,'2RM':null,'3RM':null},history:[],filled:false},
      {id:'clean-jerk',name:'Clean & Jerk',cat:'haltero',primary:{label:'1RM',value:'À renseigner',kind:'missing'},rms:{'1RM':null,'e1RM':null,'2RM':null,'3RM':null},history:[],filled:false},
      {id:'power-clean',name:'Power Clean',cat:'haltero',primary:{label:'1RM',value:'À renseigner',kind:'missing'},rms:{'1RM':null,'e1RM':null,'2RM':null,'3RM':null},history:[],filled:false},
      {id:'pullups',name:'Strict Pull-ups',cat:'gym',primary:{label:'Max reps',value:'À renseigner',kind:'missing'},metrics:{'Max reps':null,'Lesté 1RM':null,'Lesté 3RM':null,'Lesté 5RM':null},history:[],filled:false},
      {id:'ttb',name:'Toes-to-Bar',cat:'gym',primary:{label:'Max reps',value:'À renseigner',kind:'missing'},metrics:{'Max reps':null,'Unbroken':null},history:[],filled:false},
      {id:'hspu',name:'Strict HSPU',cat:'gym',primary:{label:'Max reps',value:'À renseigner',kind:'missing'},metrics:{'Max reps':null,'Unbroken':null},history:[],filled:false},
      {id:'run1k',name:'Run · 1 km',cat:'run',primary:{label:'Meilleur temps',value:'À renseigner',kind:'missing'},metrics:{'Meilleur temps':null,'Dernier temps':null},history:[],filled:false},
      {id:'run5k',name:'Run · 5 km',cat:'run',primary:{label:'Meilleur temps',value:'À renseigner',kind:'missing'},metrics:{'Meilleur temps':null,'Dernier temps':null},history:[],filled:false},
      {id:'run10k',name:'Run · 10 km',cat:'run',primary:{label:'Meilleur temps',value:'À renseigner',kind:'missing'},metrics:{'Meilleur temps':null,'Dernier temps':null},history:[],filled:false},
      {id:'row2k',name:'RowErg · 2 000 m',cat:'erg',primary:{label:'Meilleur temps',value:'À renseigner',kind:'missing'},metrics:{'Meilleur temps':null,'500 m':null,'1 000 m':null},history:[],filled:false},
      {id:'ski1k',name:'SkiErg · 1 000 m',cat:'erg',primary:{label:'Meilleur temps',value:'À renseigner',kind:'missing'},metrics:{'Meilleur temps':null,'500 m':null},history:[],filled:false},
      {id:'bike1m',name:'Assault Bike · 1 min',cat:'erg',primary:{label:'Calories',value:'À renseigner',kind:'missing'},metrics:{'Calories':null,'Puissance max':null},history:[],filled:false},
      {id:'legpress',name:'Leg Press',cat:'machine',primary:{label:'5RM',value:'130 kg',kind:'real'},rms:{'5RM':'130 kg','8RM':null,'10RM':null},source:'Machine à identifier',history:[['Référence connue','130 kg × 5']],filled:true},
      {id:'latpulldown',name:'Lat Pulldown',cat:'machine',primary:{label:'8RM',value:'À renseigner',kind:'missing'},rms:{'5RM':null,'8RM':null,'10RM':null},history:[],filled:false},
      {id:'legcurl',name:'Leg Curl',cat:'machine',primary:{label:'8RM',value:'À renseigner',kind:'missing'},rms:{'5RM':null,'8RM':null,'10RM':null},history:[],filled:false},
      {id:'duowod',name:'WOD duo · 13 août',cat:'benchmark',primary:{label:'For time',value:'57:00',kind:'real'},metrics:{'Meilleur temps':'57:00'},history:[['13 août 2026','57:00']],filled:true},
      {id:'fran',name:'Fran',cat:'benchmark',primary:{label:'For time',value:'À renseigner',kind:'missing'},metrics:{'Meilleur temps':null},history:[],filled:false},
      {id:'murph',name:'Murph',cat:'benchmark',primary:{label:'For time',value:'À renseigner',kind:'missing'},metrics:{'Meilleur temps':null,'Avec gilet':null},history:[],filled:false},
      {id:'hyroxrelay',name:'Hyrox Relay',cat:'hyrox',primary:{label:'Meilleur temps',value:'59:30',kind:'real'},metrics:{'Meilleur temps':'59:30'},history:[['Référence connue','59:30']],filled:true},
      {id:'hyroxsolo',name:'Hyrox Solo',cat:'hyrox',primary:{label:'Meilleur temps',value:'À renseigner',kind:'missing'},metrics:{'Meilleur temps':null},history:[],filled:false}
    ]
  },
  partner:{name:'Ma femme',initials:'MF',age:null,height:null,sex:'Femme',weight:null,vo2:null,
    muscles:[['Quadriceps','Élevé','high'],['Épaules','Moyen','mid'],['Dos','Moyen','mid'],['Fessiers','Élevé','high'],['Pectoraux','Faible','low']],
    profileAxes:[['Force',55],['Endurance',65],['Puissance',53],['Gymnastique',40],['Endurance musculaire',64]],
    sessions:[{dateISO:'2026-08-13',date:'13 août 2026',type:'Cross Training duo',family:'wod',duration:'57 min',rpe:'8',result:'57:00',focus:'Mixte',items:['1 km Run','Tire Push 100 m','Farmer Carry','Wall Balls 6 kg','TRX','Sandbag 20 kg','Burpees','1 km Run'],real:true}],
    refs:[
      {id:'back-squat',name:'Back Squat',cat:'force',primary:{label:'1RM',value:'À renseigner',kind:'missing'},rms:{'1RM':null,'e1RM':null,'3RM':null,'5RM':null},history:[],filled:false},
      {id:'deadlift',name:'Deadlift',cat:'force',primary:{label:'1RM',value:'À renseigner',kind:'missing'},rms:{'1RM':null,'e1RM':null,'3RM':null,'5RM':null},history:[],filled:false},
      {id:'snatch',name:'Snatch',cat:'haltero',primary:{label:'1RM',value:'À renseigner',kind:'missing'},rms:{'1RM':null,'e1RM':null,'2RM':null,'3RM':null},history:[],filled:false},
      {id:'pullups',name:'Strict Pull-ups',cat:'gym',primary:{label:'Max reps',value:'À renseigner',kind:'missing'},metrics:{'Max reps':null},history:[],filled:false},
      {id:'run5k',name:'Run · 5 km',cat:'run',primary:{label:'Meilleur temps',value:'À renseigner',kind:'missing'},metrics:{'Meilleur temps':null},history:[],filled:false},
      {id:'row2k',name:'RowErg · 2 000 m',cat:'erg',primary:{label:'Meilleur temps',value:'À renseigner',kind:'missing'},metrics:{'Meilleur temps':null},history:[],filled:false},
      {id:'legpress',name:'Leg Press',cat:'machine',primary:{label:'5RM',value:'À renseigner',kind:'missing'},rms:{'5RM':null,'8RM':null,'10RM':null},history:[],filled:false},
      {id:'duowod',name:'WOD duo · 13 août',cat:'benchmark',primary:{label:'For time',value:'57:00',kind:'real'},metrics:{'Meilleur temps':'57:00'},history:[['13 août 2026','57:00']],filled:true},
      {id:'hyroxsolo',name:'Hyrox Solo',cat:'hyrox',primary:{label:'Meilleur temps',value:'À renseigner',kind:'missing'},metrics:{'Meilleur temps':null},history:[],filled:false}
    ]
  }
};
const storeKey='sportEvolveV02';
let data;try{data=JSON.parse(localStorage.getItem(storeKey)||'null')||structuredClone(seed)}catch(e){data=structuredClone(seed)}
let current=localStorage.getItem('sportEvolveProfile')||'gregorio';if(!data[current])current='gregorio';let refCat='all';let sessionFilter='all';
const catLabels={force:'Force',haltero:'Haltérophilie',gym:'Gymnastique',run:'Running',erg:'Ergs',machine:'Machines',benchmark:'WOD benchmark',hyrox:'Hyrox'};
function save(){localStorage.setItem(storeKey,JSON.stringify(data));localStorage.setItem('sportEvolveProfile',current)}
function formatNumber(n){return String(n).replace('.',',')}
function render(){const p=data[current];$('#profileName').textContent=p.name;$('#avatar').textContent=p.initials;$('#bigAvatar').textContent=p.initials;$('#profileCardName').textContent=p.name;$('#dashboardTitle').textContent=current==='gregorio'?"Voici où en est ta semaine.":"Voici où en est sa semaine.";const now=new Date();$('#todayLabel').textContent=now.toLocaleDateString('fr-FR',{weekday:'long',day:'numeric',month:'long'});$('#weekNumber').textContent='S'+getWeekNumber(now);$('#weekSessionCount').textContent=`${p.sessions.length}`;renderWeek();renderMuscles();renderProgress();renderReferences();renderTimeline();renderProfile();$$('.profile-option[data-profile]').forEach(b=>b.classList.toggle('active',b.dataset.profile===current))}
function getWeekNumber(d){const date=new Date(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate()));date.setUTCDate(date.getUTCDate()+4-(date.getUTCDay()||7));const y=new Date(Date.UTC(date.getUTCFullYear(),0,1));return Math.ceil((((date-y)/86400000)+1)/7)}
function renderWeek(){const p=data[current];const recent=p.sessions.slice(0,4);const labels=['LUN','MAR','JEU','W-E'];$('#weekGrid').innerHTML=labels.map((l,i)=>{const s=recent[i];return `<div class="week-day ${s?'active':''}"><span class="day">${l}</span>${s?`<div class="done-dot">✓</div><b>${s.type}</b><small>${s.duration}${s.sample?' · exemple':''}</small>`:`<b>—</b><small>Libre</small>`}</div>`}).join('')}
function renderMuscles(){$('#muscleList').innerHTML=data[current].muscles.map(x=>`<div class="muscle-line"><b>${x[0]}</b><span class="load ${x[2]}">${x[1]}</span></div>`).join('')}
function renderProgress(){const p=data[current];const filled=p.refs.filter(r=>r.filled);const estimated=filled.filter(r=>r.primary.kind==='estimated');const real=filled.filter(r=>r.primary.kind==='real');const cards=[{icon:'↗',title:`${filled.length} références déjà connues`,text:'La base va gagner en valeur à mesure que tu complètes les mouvements.'},{icon:'≈',title:`${estimated.length} e1RM affiché${estimated.length>1?'s':''} séparément`,text:'Les estimations ne sont jamais confondues avec un record réellement réalisé.'},{icon:'✓',title:`${real.length} références réelles`,text:'Chronos, RM ou benchmarks effectivement réalisés.'}];$('#recentProgress').innerHTML=cards.map(c=>`<div class="card insight-card"><div class="insight-icon">${c.icon}</div><div><h3>${c.title}</h3><p>${c.text}</p></div></div>`).join('')}
function renderReferences(){const p=data[current];const list=p.refs.filter(r=>refCat==='all'||r.cat===refCat);$('#filledRefs').textContent=p.refs.filter(r=>r.filled).length;$('#missingRefs').textContent=p.refs.filter(r=>!r.filled).length;$('#referenceList').innerHTML=list.map(r=>`<button class="ref-card ${r.filled?'':'missing'}" data-refid="${r.id}" data-refcat="${r.cat}"><div class="category-dot"></div><div class="ref-name">${r.name}</div><div class="main-value">${r.primary.value}</div><div class="main-type">${r.primary.label}${r.primary.kind==='estimated'?' · estimé':''}</div><div class="ref-foot"><span>${catLabels[r.cat]}</span><b>${r.filled?'Détails ›':'À remplir ›'}</b></div></button>`).join('');$$('.ref-card').forEach(b=>b.onclick=()=>openReference(b.dataset.refid,b.dataset.refcat))}
function findRef(id,cat){return data[current].refs.find(r=>r.id===id&&r.cat===cat)}
function openReference(id,cat){const r=findRef(id,cat);if(!r)return;$('#refDetailCat').textContent=catLabels[r.cat].toUpperCase();$('#refDetailName').textContent=r.name;const metrics=r.rms||r.metrics||{};const rows=Object.entries(metrics).map(([k,v])=>{let kind='missing',label='À renseigner';if(v){kind=k==='e1RM'?'estimated':'real';label=v}return `<div class="rm-row"><div class="rm-name">${k}</div><div class="rm-value">${label}</div><span class="truth-badge ${kind}">${kind==='estimated'?'estimé':kind==='real'?'réel':'vide'}</span></div>`}).join('');const hist=(r.history||[]).map(h=>`<div class="history-point"><span>${h[0]}</span><b>${h[1]}</b></div>`).join('')||'<div class="benchmark-placeholder">Aucun historique pour le moment.</div>';$('#referenceDetailContent').innerHTML=`<div class="detail-hero"><div class="main-detail"><div><div class="kind">${r.primary.label}</div><div class="value">${r.primary.value}</div></div><span class="status">${r.primary.kind==='estimated'?'ESTIMÉ':r.filled?'RÉEL':'À RENSEIGNER'}</span></div>${r.source?`<div class="data-note">Source : ${r.source}</div>`:''}</div><div class="detail-section"><h3>Détails de la référence</h3><div class="rm-table">${rows}</div></div><div class="detail-section"><h3>Où tu te situes</h3><div class="benchmark-card"><div class="bench-top"><b>Positionnement relatif</b><span class="soft-badge">À CONNECTER</span></div><p>Sexe, âge et poids/taille seront utilisés selon le type de performance et la qualité du référentiel disponible.</p><div class="benchmark-placeholder">Percentile / niveau : — · Référentiel non encore connecté dans cette V0.2 UX.</div></div></div><div class="detail-section"><h3>Historique</h3><div class="history-row">${hist}</div></div><button class="primary wide" onclick="prefillReference('${r.name.replace(/'/g,"\\'")}')">＋ Ajouter une performance</button>`;openOverlay('referenceOverlay')}
function renderTimeline(){let arr=data[current].sessions;if(sessionFilter==='week')arr=arr.slice(0,4);else if(sessionFilter!=='all')arr=arr.filter(s=>s.family===sessionFilter);$('#timeline').innerHTML=arr.map(s=>`<div class="timeline-item"><div class="card tl-card"><div class="tl-top"><div><div class="tl-date">${s.date}${s.sample?' · EXEMPLE UX':''}</div><div class="tl-title">${s.type}</div></div><div class="tl-duration">${s.duration}</div></div><div class="tl-row">${s.items.join(' · ')}</div><div class="tl-badges"><span class="tiny">RPE ${s.rpe||'—'}</span>${s.result&&s.result!=='—'?`<span class="tiny">${s.result}</span>`:''}<span class="tiny">${s.focus}</span></div></div></div>`).join('')||'<div class="helper-card">Aucune séance dans ce filtre.</div>'}
function renderProfile(){const p=data[current];$('#profileDescriptor').textContent=[p.age?`${p.age} ans`:null,p.height?`${formatNumber(p.height)} m`:null,p.weight?`${formatNumber(p.weight)} kg`:null].filter(Boolean).join(' · ')||'Profil à compléter';$('#profileWeight').textContent=p.weight?`${formatNumber(p.weight)} kg`:'À renseigner';$('#profileVo2').textContent=p.vo2?String(p.vo2):'À renseigner';$('#profileHeight').textContent=p.height?`${formatNumber(p.height)} m`:'À renseigner';$('#profileAge').textContent=p.age?`${p.age} ans`:'À renseigner';$('#sportProfile').innerHTML=p.profileAxes.map(a=>`<div class="profile-axis"><span>${a[0]}</span><div class="bar"><i style="width:${a[1]}%"></i></div><em>${a[1]}%</em></div>`).join('')+'<div class="data-note">Aperçu UX uniquement : ces scores ne sont pas encore calculés à partir des données réelles.</div>'}
function navigate(name){$$('.page').forEach(p=>p.classList.remove('active'));const map={dashboard:'#dashboardPage',references:'#referencesPage',sessions:'#sessionsPage',program:'#programPage',profile:'#profilePage'};$(map[name]||'#dashboardPage').classList.add('active');$$('.nav-btn[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===name));window.scrollTo({top:0,behavior:'smooth'})}
$$('[data-nav]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.nav)));
$('#profileBtn').onclick=e=>{e.stopPropagation();$('#profileMenu').classList.toggle('open');$('#profileBtn').setAttribute('aria-expanded',$('#profileMenu').classList.contains('open'))};$('#viewProfile').onclick=()=>{$('#profileMenu').classList.remove('open');navigate('profile')};$$('.profile-option[data-profile]').forEach(b=>b.onclick=()=>{current=b.dataset.profile;save();$('#profileMenu').classList.remove('open');refCat='all';sessionFilter='all';resetActiveTabs();render();toast(`Profil : ${data[current].name}`)});document.addEventListener('click',e=>{if(!e.target.closest('#profileMenu')&&!e.target.closest('#profileBtn'))$('#profileMenu').classList.remove('open')});
function resetActiveTabs(){$$('#referenceTabs .tabchip').forEach(b=>b.classList.toggle('active',b.dataset.cat==='all'));$$('#sessionTabs .tabchip').forEach(b=>b.classList.toggle('active',b.dataset.sessionfilter==='all'))}
$$('#referenceTabs .tabchip').forEach(b=>b.onclick=()=>{refCat=b.dataset.cat;$$('#referenceTabs .tabchip').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderReferences()});$$('#sessionTabs .tabchip').forEach(b=>b.onclick=()=>{sessionFilter=b.dataset.sessionfilter;$$('#sessionTabs .tabchip').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderTimeline()});
function openOverlay(id){const el=$('#'+id);el.classList.add('open');el.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}function closeOverlay(id){const el=$('#'+id);el.classList.remove('open');el.setAttribute('aria-hidden','true');if(!$('.overlay.open'))document.body.style.overflow=''}$$('[data-close]').forEach(b=>b.onclick=()=>closeOverlay(b.dataset.close));$$('.overlay').forEach(o=>o.addEventListener('click',e=>{if(e.target===o)closeOverlay(o.id)}));
$('#addMain').onclick=()=>openOverlay('addOverlay');$('#addSessionSessions').onclick=()=>openOverlay('sessionOverlay');$$('[data-addmode]').forEach(b=>b.onclick=()=>{closeOverlay('addOverlay');const mode=b.dataset.addmode;openOverlay(mode==='session'?'sessionOverlay':mode==='reference'?'referenceFormOverlay':'measureOverlay')});
const now=new Date();const iso=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;$('#dateInput').value=iso;$('#measureDate').value=iso;
function exerciseRow(name='',sets='',reps='',load=''){const d=document.createElement('div');d.className='exercise-box';d.innerHTML=`<div class="exercise-row"><input placeholder="Mouvement" value="${name}"><input placeholder="Séries" inputmode="numeric" value="${sets}"><input placeholder="Reps" inputmode="numeric" value="${reps}"><input placeholder="kg / m" value="${load}"><button class="rm" type="button">×</button></div>`;d.querySelector('.rm').onclick=()=>d.remove();return d}$('#exerciseList').append(exerciseRow());$('#addExercise').onclick=()=>$('#exerciseList').append(exerciseRow());
$('#sessionForm').onsubmit=e=>{e.preventDefault();const rows=[...$('#exerciseList').querySelectorAll('.exercise-row')];const items=rows.map(r=>{const ins=r.querySelectorAll('input');const n=ins[0].value.trim();if(!n)return null;return [n,ins[1].value&&`${ins[1].value} séries`,ins[2].value&&`${ins[2].value} reps`,ins[3].value].filter(Boolean).join(' · ')}).filter(Boolean);const raw=$('#dateInput').value;const dt=raw?new Date(raw+'T12:00:00'):new Date();const type=$('#sessionType').value;const fam=type==='Running'?'run':type==='Force'?'strength':(type==='Hyrox'||type==='Cross Training')?'wod':'strength';const s={dateISO:raw,date:dt.toLocaleDateString('fr-FR',{day:'numeric',month:'long',year:'numeric'}),type,family:fam,duration:`${$('#durationInput').value||'—'} min`,rpe:$('#rpeInput').value||'—',result:$('#wodTime').value.trim()||'—',focus:type,items:items.length?items:['Séance enregistrée manuellement'],real:true};data[current].sessions.unshift(s);save();render();closeOverlay('sessionOverlay');navigate('dashboard');toast('Séance enregistrée ✓')};
window.prefillReference=name=>{closeOverlay('referenceOverlay');$('#refMovementInput').value=name;openOverlay('referenceFormOverlay')};
$('#referenceForm').onsubmit=e=>{e.preventDefault();const name=$('#refMovementInput').value.trim(),metric=$('#refMetricInput').value,value=$('#refValueInput').value.trim();if(!name||!value){toast('Renseigne le mouvement et la valeur');return}let r=data[current].refs.find(x=>x.name.toLowerCase()===name.toLowerCase());if(!r){r={id:'custom-'+Date.now(),name,cat:'force',primary:{label:metric,value,kind:'real'},rms:{[metric]:value},history:[[new Date().toLocaleDateString('fr-FR'),value]],filled:true};data[current].refs.unshift(r)}else{if(!r.rms&&!r.metrics)r.rms={};const holder=r.rms||r.metrics;holder[metric]=value;r.primary={label:metric,value,kind:'real'};r.filled=true;r.history=r.history||[];r.history.unshift([new Date().toLocaleDateString('fr-FR'),`${metric} · ${value}`])}save();render();closeOverlay('referenceFormOverlay');navigate('references');toast('Référence enregistrée ✓');$('#refMovementInput').value='';$('#refValueInput').value=''};
$('#measureForm').onsubmit=e=>{e.preventDefault();const type=$('#measureType').value,v=parseFloat($('#measureValue').value.replace(',','.'));if(Number.isNaN(v)){toast('Valeur invalide');return}if(type==='Poids')data[current].weight=v;else data[current].vo2=v;save();render();closeOverlay('measureOverlay');navigate('profile');toast(`${type} enregistré ✓`);$('#measureValue').value=''};
const suggestions={force:['Back Squat','Front Squat','Deadlift','Bench Press','Strict Press','Push Press','Barbell Row','Romanian Deadlift'],haltero:['Snatch','Power Snatch','Clean','Power Clean','Clean & Jerk','Jerk'],gym:['Strict Pull-ups','Chest-to-Bar','Toes-to-Bar','Strict HSPU','Bar Muscle-up','Ring Muscle-up','Handstand Walk'],run:['400 m','1 km','5 km','10 km','Cooper 12 min'],erg:['RowErg 500 m','RowErg 2 000 m','SkiErg 1 000 m','Assault Bike 1 min','BikeErg 10 km'],machine:['Leg Press','Leg Extension','Leg Curl','Chest Press','Lat Pulldown','Seated Row','Shoulder Press'],benchmark:['Fran','Grace','Helen','Murph','Diane','Cindy'],hyrox:['Hyrox Solo','Hyrox Doubles','Hyrox Relay']};
$('#suggestRefsBtn').onclick=()=>{const order=['force','haltero','gym','run','erg','machine','benchmark','hyrox'];$('#suggestList').innerHTML=order.map(c=>`<div class="suggest-group"><h3>${catLabels[c]}</h3><div class="suggest-items">${suggestions[c].map((x,i)=>`<div class="suggest-item"><span>${x}</span><em>${i<3?'Essentiel':'Avancé'}</em></div>`).join('')}</div></div>`).join('');openOverlay('suggestOverlay')};
$('#weightTile').onclick=()=>toast('Historique du poids : écran dédié à construire en V0.3');$('#vo2Tile').onclick=()=>toast('Historique VO₂ max : écran dédié à construire en V0.3');
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2200)}window.toast=toast;render();
